name: build

on:
  pull_request:
    paths:
      - 'build.sh'
      - '.github/workflows/build.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: ./build.sh

