name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "build"
        run: ./build.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            yr32-skinbuilder@*.osk

